diagonal_length = require ("./require_export.js")
require ("./require_export.js")
require ("./require_caching.js")
a = parseInt (Math.random()* 10)
b = parseInt (Math.random()* 10)
console.log (a)
console.log (b)
console.log (parseInt (diagonal_length (a, b)))